services:
  # A Django web service
  - type: web
    name: skillpartner
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn SkillPartner.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: SkillPartner.settings_production
      - key: DATABASE_URL
        fromDatabase:
          name: skillpartner_db
          property: connectionString

databases:
  - name: skillpartner_db
    databaseName: skillpartner
    user: skillpartner
